spring.application.name=MusicMatch
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.security.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
spring.security.jwt.expiration=86400000
spring.security.jwt.refresh-expiration=604800000

spring.mail.host=localhost
spring.mail.port=25
spring.mail.username=test@test.com
spring.mail.password=test
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

springdoc.swagger-ui.path=/api/docs
spring.jpa.open-in-view=false

aws.region=us-east-1
aws.s3.bucket-name=mock-bucket

# Spotify API
spotify.client-id=mock-client-id
spotify.client-secret=mock-client-secret
spotify.token-url=https://accounts.spotify.com/api/token
spotify.api-url=https://api.spotify.com/v1

# Async
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=20
spring.task.execution.pool.queue-capacity=100
# Actuator Health
management.health.mail.enabled=false
