spring.application.name=MusicMatch
spring.datasource.url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.security.jwt.secret=${JWT_SECRET}
spring.security.jwt.expiration=${JWT_EXPIRATION}
spring.security.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
springdoc.swagger-ui.path=/api/docs
spring.jpa.open-in-view=false
aws.region=${AWS_REGION}
aws.s3.bucket-name=${BUCKET_NAME}

# Spotify API
spotify.client-id=${SPOTIFY_CLIENT_ID}
spotify.client-secret=${SPOTIFY_CLIENT_SECRET}
spotify.token-url=https://accounts.spotify.com/api/token
spotify.api-url=https://api.spotify.com/v1

# Async
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=20
spring.task.execution.pool.queue-capacity=100
spring.task.execution.thread-name-prefix=musicmatch-async-
# Actuator Health
management.health.mail.enabled=false
